using System.Text.Json.Serialization;

namespace DocFlow.Application.Auth.DTOs;

[JsonConverter(typeof(PermisosDtoConverter))]
public record PermisosDto(
    bool Bandeja,
    bool CrearDocumento,
    bool Derivar,
    bool Firmar,
    bool Admin,
    string Reportes,
    bool DocumentosVer = false,
    bool Expedientes = false,
    bool Archivadores = false,
    bool Proveedores = false,
    bool Facturas = false,
    bool Firmas = false,
    bool Oirs = false,
    bool Despacho = false,
    bool Recibir = false,
    bool Reenviar = false,
    bool Devolver = false,
    bool Archivar = false,
    bool Anular = false,
    bool AdminUsuariosVer = false,
    bool AdminUsuariosCrear = false,
    bool AdminUsuariosEditar = false,
    bool AdminUsuariosActivar = false,
    bool AdminUsuariosDesactivar = false,
    bool AdminUsuariosResetPassword = false,
    bool AdminUsuariosBloquear = false,
    bool AdminRolesVer = false,
    bool AdminRolesCrear = false,
    bool AdminRolesEditar = false,
    bool AdminRolesEliminar = false,
    bool AdminRolesPermisos = false,
    bool AdminDepartamentosVer = false,
    bool AdminDepartamentosEditar = false,
    bool AdminCatalogosVer = false,
    bool AdminCatalogosEditar = false,
    bool AdminConfiguracionVer = false,
    bool AdminConfiguracionEditar = false,
    bool AdminIntegracionesVer = false,
    bool AdminIntegracionesEditar = false,
    bool AdminAuditoriaVer = false,
    bool AdminRespaldosVer = false,
    bool AdminRespaldosCrear = false,
    bool AdminRespaldosEditar = false,
    bool AdminRespaldosConfigurar = false,
    bool AdminRespaldosDescargar = false,
    bool AdminRespaldosRestaurar = false,
    bool AdminNumeracionVer = false,
    bool AdminNumeracionEditar = false,
    bool AdminPlantillasNumeracionVer = false,
    bool AdminPlantillasNumeracionEditar = false,
    bool OrdenesCompraVer = false,
    bool OrdenesCompraCrear = false,
    bool OrdenesCompraAprobar = false,
    bool OrdenesCompraAnular = false);
